Index: akaikkr-20210506/makefile
===================================================================
--- akaikkr-20210506.orig/makefile	2021-03-29 12:13:09.000000000 +0900
+++ akaikkr-20210506/makefile	2021-05-15 16:22:39.367327121 +0900
@@ -12,15 +12,15 @@
 #
 #######################################
 # specify the fortran compiler
-fort = ifort
-#fort = gfortran
+#fort = ifort
+fort = gfortran
 #######################################
 ifeq ($(fort),ifort)
 	flag = -O2 -mcmodel=medium
 	omp = -qopenmp
 	nomp = -qopenmp-stubs
 else
-	flag = -O2 
+	flag = -O2 -Wall
 	omp = -fopenmp -w
 	nomp =
 endif
@@ -267,3 +267,15 @@
 
 spc: source/spc.f
 	$(fort) $(flag) $(omp) -o $@ $<
+
+install: $(program) gpd spc
+	install -d $(DESTDIR)/usr/bin
+	install -d $(DESTDIR)/usr/share/akaikkr/in
+	install -d $(DESTDIR)/usr/share/akaikkr/util
+	install $(program) gpd spc $(DESTDIR)/usr/bin
+	cp -p in/* $(DESTDIR)/usr/share/akaikkr/in
+	cp -p util/* $(DESTDIR)/usr/share/akaikkr/util
+	chmod 644 $(DESTDIR)/usr/share/akaikkr/in/* $(DESTDIR)/usr/share/akaikkr/util/*
+clean:
+	rm -f $(program) gpd spc source/*.o
+
